### ISSUE TITLE
C++ library error

### ISSUE THREAD

**Issue by arf20** [Cyuria/discord.nvim#24]
```
Discord: Something went wrong while copying and/or loading library files
Discord.nvim Failed to start because the C++ library could not be copied or is in use
```
I have no clue how this plugin, or Discord RPC works. Just reporting this. And maybe you know how to resolve it.

**Comment by cyuria** [comment]
Yeah its not a problem, basically if you have multiple instances of neovim running, it fails because its already running, I should probably put something about it in the readme or somewhere

**Comment by cyuria** [comment]
I've updated the readme in the latest commit 97d7d30 to reference this

**Comment by arf20** [comment]
The thing is... I don't think I had any other instance running. I'll check later, thanks.

**Comment by cyuria** [comment]
Basically there is C++ code which gets compiled and then there is lua binding code, which runs the C++ code. That error message is a problem which occurs when lua can't access the compiled library, which I get whenever neovim is already running, otherwise it could be something like a file permission error which I'd have to look into
