### ISSUE TITLE
Unable to make it work

### ISSUE THREAD

**Issue by Shatur** [Cyuria/discord.nvim#26]
I use ArchLinux. I installed the plugin, compiled the binary and called `require('discord').setup()`. But the presence doesn't work. I tried calling `:DiscordInit` manually, but Neovim just crashes.
What logs I can provide?

**Comment by cyuria** [comment]
I have only tested the plugin for windows, because I only use discord from my laptop and PC which both run windows, but I just found that calling `:DiscordInit` while the presence plugin is already running causes my neovim to crash too. It may be something to do with the underlying RPC library which is used by discord not being able to communicate with discord on your computer specifically.

Can you get any other discord rich presence applications working? (e.g. Games, other discord rich presence plugins, etc)
I believe there is a python library for rich presence communication if you want to try a basic example from that. (I found it: https://pypi.org/project/pypresence/)

I'll try to add a debug mode or something which adds better logging when I get time

**Comment by Shatur** [comment]
> Can you get any other discord rich presence applications working?

https://github.com/andweeb/presence.nvim works for me. But I looking for an alternative since it introduces stuttering.

**Comment by cyuria** [comment]
Sorry for not getting back to you sooner, I haven't really had time this week for anything. I'll see if I can do something about the debug logging on the weekend maybe.

Is discord already running when you start neovim (or whenever you first make the call to discordinit)? Because if it isn't that would likely be the source of the problem, as for some reason the IPC channel doesn't play nicely with discord if discord is started after the plugin is loaded/initialised.

**Comment by Shatur** [comment]
> Is discord already running when you start neovim (or whenever you first make the call to discordinit)

It was running.

**Comment by cyuria** [comment]
> It was running.

Ok thanks, I'll see what I can do

**Comment by Shatur** [comment]
I currently switching to https://github.com/ObserverOfTime/nvimcord, also works quite fast.

**Comment by cyuria** [comment]
Yeah thats probably a good idea, I don't really have much time to maintain this plugin, sorry about that. It seems like ObserverOfTime/nvimcord will have better support and more features.

I'll close this issue, if ever feel the need to use this plugin instead for whatever reason, I'll be happy to to help you out, or just submit a PR if you want to instead. Hopefully by then I'll have added better debugging.
